

#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_


#define F_OSC		8000000UL
#define BUAD_RATE	9600UL

#define RX_STATE	RX_ENABLE
#define TX_STATE	TX_ENABLE

#define RX_INTERRUPT_STATE	RX_INTERRUPT_DISABLE
#define TX_INTERRUPT_STATE	TX_INTERRUPT_DISABLE

#define UART_MODE		UART_ASYNCRONOUS

#define PARITY_MODE		PARITY_DISABLE

#define STOP_BITS_NUM	ONE_STOP_BIT

#define DATA_BITS_NUM	EIGHT_DATA_BITS

#endif /* UART_CONFIG_H_ */