

#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_


#define SPI_STATE				SPI_ENABLE
#define SPI_INTERRUPT_STATE		SPI_INTERRUPT_DISABLE

#define SPI_DEVISE_MODE			SPI_SLAV

#define SPI_CLK_PRESCALER		SPI_CLK_PRESCALER_128
#define SPI_CLK_POLARITY_MODE	SPI_CLK_POLARITY_LOW
#define SPI_CLK_PHASE_MODE		SPI_CLK_PHASE_LOW

#define SPI_DATA_TRANFER_MODE	SPI_TRANSFER_LSB_FIRST

#endif /* SPI_CONFIG_H_ */