

#ifndef TIMER0CONFIG_H_
#define TIMER0CONFIG_H_


#define F_OSC_MHZ		8

#define TIMER0_MODE								TIMER_NORMAL_MODE
#define TIMER0_WAVE_GENERATION_MODE				TIMER_WAVE_GENERATION_DISABLE
#define TIMER0_PRESCALER						TIMER_PRESCALER_1024
#define TIMER0_OVERFLOW_INTERRUPT_MODE			TIMER_OVERFLOW_INTERRUPT_ENABLE
#define TIMER0_COMPARE_MATCH_INTERRUPT_MODE		TIMER_COMPARE_MATCH_INTERRUPT_DISABLE
#define TIMER0_MAX_TICKS						256



#endif /* TIMERCONFIG_H_ */